### PR TITLE
Weighting the samples by their alpha coverage (draft)

### PR DESCRIPTION
**Pull request by Level3Manatee**
Hello,

first of all thank you for making this! I was recently thinking about the technique and it's nice to have a solid foundation to build upon.

One detail though does not seem to align with the steps outlined in the God of War talk -
>2. At each step we scale it down to half of its size, **weighting the samples by their alpha coverage.**

My interpretation is that this is to discard pixel values that are not inside the coverage mask.

A quick example why this is beneficial:
<p> </p>

Compositing linearly scaled down mip levels (current implementation), we get this:

But that would potentially result in some darker tones bleeding into the shape, which is usually avoided using edge dilation:

Instead, the color values outside of coverage should be discarded when calculating the pixel average when scaling down.

I first tried an implementation using NumPy, where I did a value by value calculation, but that turned out to be too slow (best version was 2x the run time of the current implementation). What also works however is this approach:
1. Multiply color by alpha coverage, to zero out any color information outside of coverage
2. Then scale down color and coverage mask linearly (Image.reduce is perfect for that, Image.resize gave me issues)
3. Now re-normalize the color using the mask, essentially `color / mask`

The result:

This PR draft contains two variants
1. Using your method of directly compositing the layers
2. Using the method described in the God of War talk, which cumulatively processes and stores the mip levels and then composites them

The second variant has been ~significantly~ faster in my tests (which makes sense, as progressively less pixels have to be considered during scaling), but of course uses more RAM. The pure Pillow variant has some smaller issues with color precision, which I think is a result of cumulative rounding errors, since this is all done in uint8. The NumPy+Pillow variant is a little slower, but works with 32 bit precision.

Some numbers (a few 8 bit PNG images 1K to 8K, single thread):

1. Direct composition

| Method  | Time |
| :- | -: |
| Current | 44.82 s |
| Weighted | 40.32 s |

3. Cumulative

| Method  | Time |
| :- | -: |
| Walking Weighted | 38.90 s |
| Walking Weighted (NumPy) | 45.65 s |

### CODE REVIEW

**Comment by Level3Manatee** [comment]
Actually found a fast-ish way to do this with NumPy

**Comment by Level3Manatee** [comment]
Ok, the weighted adaption of the original implementation was unnecessarily slow, got it 25% faster by pre-multiplying only once, so that one looks pretty attractive now.

The NumPy version could be interesting for replacing Pillow with e.g. OpenCV or maybe SciKit, for processing images > 8 bit. Very possible that it could be faster still, haven't done too much with NumPy before.

**Comment by Level3Manatee** [comment]
Did some further testing and found incorrect results for a very dark texture with all but the NumPy variant ... I'm guessing rounding issues. Will look into it a bit more.
Numpy:
correct
Others:
incorrect

**Comment by secarri** [comment]
Hello Jan! 

I was about to report this issue and had a chance to look into it yesterday. As we discussed, I’ve started porting the code to C#. However, I don’t expect significant speed improvements initially. For processing times under one second, C or C++ would be better. Python and C# are currently similar in performance. I’ve pushed my changes, though they’re not yet in the main branch. Everything is working, but some parts are still a bit slow. If you end up making a C++ version let me know :)

Your Fork             |  Expected, currently in the new branch
:-------------------------:|:-------------------------:
 | 


New branch, still WIP, will push it to main early next week: [csharp-refactor-python-binding](https://github.com/secarri/MipFlooding/tree/csharp-refactor-python-binding)

**Comment by Level3Manatee** [comment]
Yeah essentially the issue is with the python-specific optimization route I took (pre-multiplying, using natively implemented scaling to calculate the average, then re-normalize), since with images that have little coverage, that is bound to run into precision issues at high resolutions (as averaging a mostly black image will yield very small numbers). Not really an issue with the walking approach though, especially at 32 bit precision (NumPy). Going to delete the other variants and fix the non-NumPy version and then call this one finished I guess. ;)

**Comment by Level3Manatee** [comment]
I decided to only keep the NumPy variant, as that one produces the most accurate results.

Output looks like this now:


The darkening was a result of the way masks were imported (mask is in R channel of an RGB image, converted to grayscale that makes a very dark mask).

Not sure when I'll get to a C++ implementation, but I've never written a Python<->Native integration so that definitely sounds interesting. ;) Thank you for the feedback, closing this now.

**Addendum 2024-08-31:**
The C++ implementation is going to be finished soon and is quite fast (< 100 ms processing for 4K single-threaded, < 50 ms multi-threaded, or around 300-400 ms for loading, processing, and saving the file with Python).

I have found that the coverage mask needs to be treated as a binary mask to yield good results. In practice this means:
1. Multiply image with binary mask to remove any unnecessary color information
2. Scale down in steps of 2, averaging color pixels and mask pixels, then normalize (divide by mask), and re-binarize mask (in the low level implementation, I sum the mask and color values, divide color value sum by mask sum, and then save the mask sum as 1 if it is > 0)
3. Composite up in steps of 2, and in the last step composite original on top

For the texture above, the result then looks like this:

**Pull request closed without merging**
